### ISSUE TITLE
Issue with bread crumbs on resume 

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#107]
I think it only happens if you come back to the app after some time, e.g. when it goes out of memory?

It's as if it forgots the path of the first bread crumb, which holds /storage/emulated/0, and thinks the path is /0?

![screenshot_2015-02-20-12-00-29](https://cloud.githubusercontent.com/assets/1820165/6306344/42a7dbfc-b8f8-11e4-82b2-b0ce77bb4d29.png)

**Comment by arkon** [comment]
Makes sense since it relies on the back stack. It's probably particularly bad on Lollipop because of the memory issues.
On Feb 20, 2015 1:02 PM, Aidan Follestad <notifications@github.com> wrote:I think it only happens if you come back to the app after some time, e.g. when it goes out of memory?

It's as if it forgots the path of the first bread crumb, which holds /storage/emulated/0, and thinks the path is /0?

**Comment by afollestad** [comment]
Well, the path is saved in strings in the bread crumbs themselves, not in
the fragments. So it's very weird.

**Comment by plusCubed** [comment]
Confirmed: Turn on Don't Keep Activities in the developer options and it happens every time

**Comment by plusCubed** [comment]
#81 seems to be happening too...

**Comment by plusCubed** [comment]
@afollestad @arkon Fixed: the context of the `File` wasn't set, so it couldn't check if the path was internal storage, sdcard, root, etc.

I'm going to reopen #81 though.
