### ISSUE TITLE
MrVector causes an enormous amount of OutOfMemory exceptions

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#135]
130 users experienced crashes for the previous version

**Comment by plusCubed** [comment]
Hmm... switch to an SVG rendering library? I use one in my own app, and I haven't seen any issues so far, but with the amount of icons in Cabinet I'm not so sure. https://code.google.com/p/androidsvg/
Or perhaps one of the libraries that convert SVG to Java code, like this one: https://github.com/racsdragon/android-svg-code-render. I'm not so sure about this either since it will increase the executable code size significantly.
Or switch back to using bitmaps, just really high resolution ones so it's smooth.

What do you think?

**Comment by afollestad** [comment]
Hmmm, still trying to brainstorm what would be best for this. It's obviously a very severe bug at this point.

**Comment by afollestad** [comment]
This should solve the issue

https://github.com/afollestad/cabinet/commit/f31a760464424f36d34b679cadc59f5dbf8fdcd7
