### ISSUE TITLE
Paste occasionally not working

### ISSUE THREAD

**Issue by alexsmithfanning** [afollestad/cabinet-issue-tracker#241]
When something is copied and you try to paste it, the FAB will expand as if in its normal state.

**Comment by alexsmithfanning** [comment]
And after something is pasted, the file size counts to zero until the directory is exited and entered again.

**Comment by afollestad** [comment]
Yeah, I noticed this once too, still trying to get to the bottom of it

**Comment by afollestad** [comment]
Oddly enough, I can't make this bug happen now that I'm trying

**Comment by alexsmithfanning** [comment]
Try pasting into something with a lot of files in it, say forty or more. Then it should happen every time.

**Comment by plusCubed** [comment]
Because the file attributes (cached in `FileInfo`) of a `LocalFile` comes from running `ls -l` in the directory of the file (which isn't done when just copying/adding a file), the file attributes are not initialized. To fix this, I added the `initFileInfo()` to `LocalFile` which runs `ls -l` just on one file to get its attributes.

**Comment by plusCubed** [comment]
Woops, related but wrong issue.

**Comment by afollestad** [comment]
I can't seem to reproduce this any longer, do you think you fixed it @plusCubed?

**Comment by plusCubed** [comment]
@afollestad I didn't address anything about this in particular.

**Comment by Rhedox** [comment]
I noticed it when trying to move files from the internal sd to an external sd card.
