### ISSUE TITLE
New FileInfo stuff causes the wrong file length to be displayed when a local file is pasted

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#243]
The File that's inserted into the adapter is the file returned by `File#copyFile`

**Comment by plusCubed** [comment]
Because the file attributes (cached in `FileInfo`) of a `LocalFile` comes from running `ls -l` in the directory of the file (which isn't done when just copying/adding a file), the file attributes are not initialized. To fix this, I added the `initFileInfo()` to `LocalFile` which runs `ls -l` just on one file to get its attributes.
