### ISSUE TITLE
Vector graphics seem low-res

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#78]

**Comment by plusCubed** [comment]
Found the solution/workaround: the width and height of the vector needs to be high-res. I'm fairly certain it'll kill performance on lower-end devices though. I think switching to something like [androidsvg](https://code.google.com/p/androidsvg/) is more viable. I'll keep this issue open while I work on that.

**Comment by afollestad** [comment]
I think the reason the icons look small is because the thumbnail in the actual layout is 44dp and the vectors are set to 24dp

**Comment by afollestad** [comment]
Maybe not, attempting to change the view port width or height makes the icons even smaller

**Comment by plusCubed** [comment]
The view port shouldn't be changed in any case (it's the canvas the vector points/paths are drawn on, e.g. 24 by 24, then scaled to the actual size without losing quality). It's just that the icons have a padding inside (just like before we changed to vectors), so it doesn't line up with the drawer icon, just like before. I don't think it should be moved left to line up, since some other icons won't line up. The way Solid Explorer solved this was by putting a circle around everything (like [here](http://www.google.com/design/spec/components/lists.html#lists-content))

**Comment by plusCubed** [comment]
Actually, I'll just move it left to line it up. I'm matching the list dimensions up with the guidelines, so this'll be part of that.

**Comment by afollestad** [comment]
Oh okay cool, sounds good

**Comment by afollestad** [comment]
Putting a circle around icons (not including images and APK thumbnails) might look nice actually.

**Comment by arkon** [comment]
Might look really annoying if it's usually circles and then you suddenly have your squares and irregular APK icon shapes though. It's almost more consistent to have inconsistent shapes.

**Comment by afollestad** [comment]
True
