### ISSUE TITLE
Search underline and cursor colour

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#85]
![screenshot_2015-02-18-07-18-14](https://cloud.githubusercontent.com/assets/7706853/6243279/61045aa0-b73e-11e4-93c7-972340d84a7b.png)

It'd look better if the colour of the underline and the cursor would match up with the colour of the icons and the text in the action bar, don't you think?

**Comment by afollestad** [comment]
Unfortunately that's not possible, you can't change those colors at runtime

**Comment by arkon** [comment]
Might actually be possible: http://www.jayway.com/2014/06/02/android-theming-the-actionbar/

**Comment by afollestad** [comment]
That's a little outdated. With Material theming and appcompat, they source the themes from a different location.

Although, if I could get a reference to the TextView, a color filter could be applied. But that requires hacky reflection.

**Comment by arkon** [comment]
Well all themes are technically themable.
On Feb 26, 2015 2:25 PM, Aidan Follestad <notifications@github.com> wrote:That's a little outdated. With Material theming and appcompat, they source the themes from a different location.

Although, if I could get a reference to the TextView, a color filter could be applied. But that requires hacky reflection.

**Comment by afollestad** [comment]
@arkon the underline of edit texts with Material design are derived from the `colorAccent` attribute of the Activity theme. You can't change that at runtime, styles.xml is static.

But it is indeed possible to force the color to change by applying a color filter, but again, reflection is needed since the TextView is a private view hidden deep within the SearchView.
